apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {appName}
  namespace: {namespace}
  labels:
    app: {appName}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      name: {appName}
      labels:
        app: {appName}
    spec:
      containers:
      - name: {appName}
        envFrom:
        - configMapRef:
            name: {appName}
        env:
        - name: BING_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: {appName}
              key: BING_MAPS_API_KEY
        - name: IRMA_API_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: {appName}
              key: IRMA_API_SERVER_KEY
        - name: IRMA_API_SERVER_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: {appName}
              key: IRMA_API_SERVER_PUBLIC_KEY
        image: {image}
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 4000
          protocol: TCP
