apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {appName}
  namespace: {namespace}
  labels:
    app: {appName}
spec:
  tls:
  - hosts:
    - {appName}.appx.cloud
    secretName: wildcard-appx-cloud-cert
  rules:
  - host: {appName}.appx.cloud
    http:
      paths:
      - backend:
          serviceName: {appName}-frontend
          servicePort: 80
        path: /
      - backend:
          serviceName: {appName}
          servicePort: 4000
        path: /api
