apiVersion: v1
kind: ConfigMap
metadata:
  name: {appName}
  namespace: {namespace}
  labels:
    app: {appName}
data:
  REDIS_HOST: "diva-redis-redis"
  REDIS_PORT: "6379"
  USE_REDIS: "false"
  BASE_URL: "https://int-diva-js-reference-3p.appx.cloud"
  IRMA_API_SERVER_URL: "https://int-diva-irma-api-server.appx.cloud"
  JWT_DISCLOSURE_ALGORITHM: 'none'
  JWT_DISCLOSURE_ISSUER: 'diva'
  JWT_SIGNATURE_ALGORITHM: 'none'
  JWT_SIGNATURE_ISSUER: 'diva'
  JWT_ISSUE_ALGORITHM: 'none'
  JWT_ISSUE_ISSUER: 'diva'
